// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asjblhwsjyznblcekqko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzamJsaHdzanl6bmJsY2VrcWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NTIxOTUsImV4cCI6MjA1MzQyODE5NX0.tlakyDKCN0ll70m7Uscf7mKTYQU-4_ZmGuLu4etJlK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);